//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOR
    {
        public AUTOR()
        {
            this.CARTEs = new HashSet<CARTE>();
        }
    
        public int AutorId { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
    
        public virtual ICollection<CARTE> CARTEs { get; set; }
    }
}
